apiVersion:  monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agenda-monitor
  namespace: agenda
spec:
  selector:
    matchLabels:
      app: backend-service
  endpoints:
  - port: backend-port
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agenda-frontend-monitor
  namespace: agenda
spec:
  selector:
    matchLabels:
      app: frontend-service # S'assurer que le sÃ©lecteur correspond au label du Service Frontend
  endpoints:
  - port: frontend-port  # Doit correspondre au nom du port dans le service frontend-service
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: agenda-rules
  namespace: agenda
spec:
  groups:
  - name: agenda.rules
    rules:
    - alert: BackendDown
      expr: up{job="agenda-backend"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Backend service is down"
    - alert: HighResponseTime
      expr: http_request_duration_seconds > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"