apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: agenda
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      # Job pour la surveillance des nœuds et de Kubernetes (utile pour le contexte)
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
          - role: cadvisor

      # Job principal pour l'application backend (utilisation de la découverte de Pods)
      - job_name: 'agenda-backend'
        # Utilise la découverte de service pour trouver tous les Pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['agenda']
        relabel_configs:
          # 1. Garde uniquement les Pods avec l'annotation prometheus.io/scrape = true
          # Ceci filtre les pods du backend (mariadb et frontend n'ont pas cette annotation)
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          
          # 2. Remplace le chemin des métriques par l'annotation prometheus.io/path (/metrics)
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            
          # 3. Utilise le port spécifié par l'annotation (8000) pour la connexion
          # Ceci transforme l'adresse du Pod (ex: 10.42.0.1:10250) en (ex: 10.42.0.1:8000)
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+):(?:\d+)
            replacement: ${1}:$$1